In [ ]:
import pandas as pd

In [8]:
df = pd.read_csv('data/stanford-hCMST.tsv', sep='\t')

print(f"Dataset Shape: {df.shape}")
display(df.head())

Dataset Shape: (3510, 725)

,CASEID_NEW,W3_WEIGHT,W3_WEIGHT_LGB,W3_COMBO_WEIGHT,W3_ATTRITION_ADJ_WEIGHT,W2_WEIGHT_GENPOP,W2_WEIGHT_LGB,W2_COMBO_WEIGHT,W2_ATTRITION_ADJ_WEIGHTS,W1_WEIGHT_COMBO,...,P20_PPPA1634,P20_PPPA1902,P20_PPPA1903,P20_PPPA1904,P20_PPP22001,P20_PPPA1905,P20_PPPA1648,P20_PPP20072,P20_PPP20071,P20_PPP2DATE2020
0,53001,.4422,,.4953084588051,.400184631348,.3856,,.4376695454121,.3803511857986,0.426861,...,2,0,1,0,0,0,13,6,,20210506
1,71609,.8284,,.9278913140297,.879257798195,.9196,,1.0437783002853,.9539480209351,1.295508,...,2,0,1,0,0,0,2,5,1,20201118
2,106983,.8255,,.9246429800987,.7064666152,.7748,,.8794252276421,.7246816754341,1.126573,...,1,1,0,0,0,0,1,4,2,20210429
3,121759,,,,,.9177,,1.0416216850281,.7930925488472,0.933440,...,1,1,0,0,0,0,11,2,1,20210507
4,158083,.881,,.9868085384369,.655467092991,.8697,,.9871400594711,.7354734539986,0.931291,...,1,1,0,0,0,0,13,6,,20210602

In [10]:
target_columns_dict = {
    'W1_PPAGE': "Subject's age", 
    'W1_PPAGE': "Subject's age Category", # Actual Age is anonymized.
    'W1_Q9': "Partner's age", # Doesn't give actual age. 
    'W1_SUBJECT_RACE': "Subject's race",
    'W1_Q6B': "Partner's race",
    'W1_INTERRACIAL_5CAT': "Interracial relationship category",
    'W1_Q6A': "Hispanic origin of partner",
    'W1_PPGENDER': "Subject's gender",
    'W1_Q4': "Partner's gender",
    'W1_ATTRACTION': "Attraction",
    'W1_PPEDUC': "Subject's education",
    'W1_Q10': "Partner's education",
    'W1_PPREG9': "Region", # Key can be found in 38873-0001-Report.pdf, page 415
    'W1_PPWORK': "Subject's employment status", # "Are you currently working? "
    'W1_Q23': "Earn more money?",
    'W1_Q25': "Same high school?",
    'W1_Q26': "Same college?",
    'W1_Q27': "Grew up same city?", # Q27: "Grew up in same city/town?"
    'W1_Q19': "Living Together", # Q19: "Are you currently living with your partner?"
    'W1_MARRIED': "Married at baseline",
    'W1_Q34': "Quality of Relationship?" # Q34: "How would you describe the quality of your relationship with partner?"
}

Filter Down to only participant Info and Answers

In [11]:
filtered_columns = list(target_columns_dict.keys()) 
df_w1_only = df[filtered_columns]

Rename Columns to be more readable

In [13]:
df_w1_only = df_w1_only.rename(columns=target_columns_dict)

In [14]:
df_w1_only

,Subject's age Category,Partner's age,Subject's race,Partner's race,Interracial relationship category,Hispanic origin of partner,Subject's gender,Partner's gender,Attraction,Subject's education,Partner's education,Region,Subject's employment status,Earn more money?,Same high school?,Same college?,Grew up same city?,Living Together,Married at baseline,Quality of Relationship?
0,1,41,3,1,1,1,2,1,1,1,1,3,1,3,1,,1,1,1,1
1,1,71,1,1,0,1,2,1,1,1,1,9,1,3,1,1,1,1,1,1
2,1,41,1,1,0,1,1,2,1,1,1,9,1,1,2,2,2,1,1,1
3,1,51,1,4,1,1,1,2,1,1,1,2,1,3,2,,2,1,1,1
4,1,31,1,1,0,1,1,2,1,1,1,8,1,1,2,2,2,,0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3505,1,21,1,1,0,1,2,1,2,1,1,8,1,3,2,,2,1,1,1
3506,1,41,1,2,1,1,2,2,3,1,1,5,2,3,2,,2,2,0,1
3507,1,21,1,1,0,1,2,1,3,1,1,3,1,1,2,,1,2,0,1
3508,1,31,2,2,0,1,2,2,4,1,1,5,1,1,2,2,2,1,0,2
3509,1,10,3,1,1,1,2,2,5,1,1,1,1,4,2,,2,2,0,1

In [15]:
df_w1_only.to_csv('hCMST_filtered.csv', index=False)